name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [2.7.13]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10).replace('v', '')
            core.setOutput('tag', tag)
            console.log(tag)

      - name: Add version to package.json
        uses: jaywcjlove/github-action-package@main
        with:
          path: "./deno.json"
          data: |
            {
              "version": "${{ steps.set_version.outputs.tag }}"
            }

      - name: Publish package
        run: npx jsr publish --allow-dirty --no-check
